In [11]:
import pandas as pd
df=pd.read_csv("C:/Users/user/Downloads/archive/diabetes_prediction_dataset.csv")

In [12]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [13]:
print(df.head())

   gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19
1  Female  54.0             0              0         No Info  27.32
2    Male  28.0             0              0           never  27.32
3  Female  36.0             0              0         current  23.45
4    Male  76.0             1              1         current  20.14

   HbA1c_level  blood_glucose_level  diabetes
0          6.6                  140         0
1          6.6                   80         0
2          5.7                  158         0
3          5.0                  155         0
4          4.8                  155         0

In [14]:
df["heart_disease"]

0        1
1        0
2        0
3        0
4        1
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: heart_disease, Length: 100000, dtype: int64

In [15]:
print(type(df))

<class 'pandas.DataFrame'>

In [16]:
df.tail()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  str
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  str
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), str(2)
memory usage: 6.9 MB

In [18]:
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='str')

In [19]:
df.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [24]:
df.shape

(100000, 9)

In [25]:
df.size

900000

In [26]:
df.mean

<bound method DataFrame.mean of        gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19
1      Female  54.0             0              0         No Info  27.32
2        Male  28.0             0              0           never  27.32
3      Female  36.0             0              0         current  23.45
4        Male  76.0             1              1         current  20.14
...       ...   ...           ...            ...             ...    ...
99995  Female  80.0             0              0         No Info  27.32
99996  Female   2.0             0              0         No Info  17.37
99997    Male  66.0             0              0          former  27.83
99998  Female  24.0             0              0           never  35.42
99999  Female  57.0             0              0         current  22.43

       HbA1c_level  blood_glucose_level  diabetes
0              6.6                  140         0
1              6.6                   80         0
2              5.7                  158         0
3              5.0                  155         0
4              4.8                  155         0
...            ...                  ...       ...
99995          6.2                   90         0
99996          6.5                  100         0
99997          5.7                  155         0
99998          4.0                  100         0
99999          6.6                   90         0

[100000 rows x 9 columns]>

In [27]:
df["age"].mean()

np.float64(41.885856)

In [28]:
df["heart_disease"].median()

np.float64(0.0)

In [30]:
df["blood_glucose_level"].mode()

0    130
Name: blood_glucose_level, dtype: int64

In [31]:
df["age"].var()

np.float64(507.008077804042)

In [32]:
df["age"].std()

np.float64(22.51683987161702)

In [33]:
df['bmi'].min()

np.float64(10.01)

In [34]:
df['bmi'].max()

np.float64(95.69)

In [35]:
df['bmi'].count()

np.int64(100000)

In [36]:
df["bmi"].unique()

array([25.19, 27.32, 23.45, ..., 59.42, 44.39, 60.52], shape=(4247,))

In [38]:
df['bmi'].value_counts()

bmi
27.32    25495
23.00      103
27.12      101
27.80      100
24.96      100
         ...
52.97        1
12.26        1
59.42        1
44.39        1
60.52        1
Name: count, Length: 4247, dtype: int64

In [56]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [40]:
df.sum()

gender                 FemaleFemaleMaleFemaleMaleFemaleFemaleFemaleMa...
age                                                            4188585.6
hypertension                                                        7485
heart_disease                                                       3942
smoking_history        neverNo InfonevercurrentcurrentneverneverNo In...
bmi                                                           2732076.71
HbA1c_level                                                     552750.7
blood_glucose_level                                             13805806
diabetes                                                            8500
dtype: object

In [46]:
df.duplicated().sum()

np.int64(3854)

In [47]:
df[['age','blood_glucose_level']]

        age  blood_glucose_level
0      80.0                  140
1      54.0                   80
2      28.0                  158
3      36.0                  155
4      76.0                  155
...     ...                  ...
99995  80.0                   90
99996   2.0                  100
99997  66.0                  155
99998  24.0                  100
99999  57.0                   90

[100000 rows x 2 columns]

In [48]:
df.sort_values("blood_glucose_level")

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
27,Male,40.0,0,0,former,27.85,5.8,80,0
99969,Female,30.0,0,0,never,22.88,4.5,80,0
43532,Male,7.0,0,0,No Info,16.63,6.2,80,0
43535,Male,60.0,0,0,current,25.26,5.7,80,0
43512,Male,15.0,0,0,No Info,20.33,3.5,80,0
...,...,...,...,...,...,...,...,...,...
47259,Male,44.0,0,1,ever,25.15,5.7,300,1
72653,Male,60.0,0,0,current,41.97,8.2,300,1
199,Female,43.0,0,0,never,26.71,6.5,300,1
99938,Male,55.0,0,1,former,30.42,6.2,300,1
47391,Male,46.0,0,0,never,47.75,6.5,300,1

In [50]:
df.iloc[0:5:3]

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
3,Female,36.0,0,0,current,23.45,5.0,155,0

In [51]:
df[df["age"]>56]

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
7,Female,79.0,0,0,No Info,23.86,5.7,85,0
12,Female,78.0,0,0,former,36.05,5.0,130,0
13,Female,67.0,0,0,never,25.69,5.8,200,0
...,...,...,...,...,...,...,...,...,...
99984,Male,80.0,1,0,No Info,20.96,6.6,85,0
99986,Female,63.0,0,0,never,29.01,4.8,145,0
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [55]:
df.rename(columns={"age":"age_years"})

,gender,age_years,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [63]:
df.drop("age",axis=1)

,gender,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,0,1,never,25.19,6.6,140,0
1,Female,0,0,No Info,27.32,6.6,80,0
2,Male,0,0,never,27.32,5.7,158,0
3,Female,0,0,current,23.45,5.0,155,0
4,Male,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...
99995,Female,0,0,No Info,27.32,6.2,90,0
99996,Female,0,0,No Info,17.37,6.5,100,0
99997,Male,0,0,former,27.83,5.7,155,0
99998,Female,0,0,never,35.42,4.0,100,0
99999,Female,0,0,current,22.43,6.6,90,0

In [64]:
df.groupby("bmi")

In [65]:
df.groupby("bmi")["HbA1c_level"].mean()

bmi
10.01    6.0
10.08    6.1
10.14    6.1
10.19    6.5
10.21    5.7
        ...
88.72    7.0
88.76    6.2
91.82    6.0
95.22    4.5
95.69    6.1
Name: HbA1c_level, Length: 4247, dtype: float64

In [67]:
df["HbA1c_level"].unique()

array([6.6, 5.7, 5. , 4.8, 6.5, 6.1, 6. , 5.8, 3.5, 6.2, 4. , 4.5, 9. ,
       7. , 8.8, 8.2, 7.5, 6.8])

In [ ]:
pd.concat